### ISSUE TITLE
Request: Support for power setting on AB-H1500WIFI

### ISSUE THREAD

**Issue by ltjessem** [Danielhiversen/pymill#24]
This oil-filled heater has low-medium-high power that can be set in the app, is this possible to control via HA?

**Comment by Danielhiversen** [comment]
It should be possible if someone can find api call.

What happens now? Does it always change to low power?

Could you try to changehttps://github.com/Danielhiversen/pymill/blob/master/mill/__init__.py#L363
https://github.com/Danielhiversen/pymill/blob/master/mill/__init__.py#L363

**Comment by ltjessem** [comment]
Right now it doesn't change the power setting at all, it remains at whatever it's been set to via the app. I'll try playing with powerLevel when I get the chance and report back.

**Comment by Danielhiversen** [comment]
Great.

It will only call that function if you you turn the heater on/off or the fan.

**Comment by Danielhiversen** [comment]
Closing this, since the library now uses a new API from mill
