### ISSUE TITLE
some parts of the API stopped working

### ISSUE THREAD

**Issue by ahti123** [Danielhiversen/pymill#82]
For example devices/{id}/statistics does not return any data. Basically only a list of houses works, anything else is either empty or 404 error.
Edit: customer/auth/sign-in works, too, obviously.

**Comment by Danielhiversen** [comment]
What functions in the library are you using? `fetch_stats` ?

**Comment by ahti123** [comment]
Haven't looked at the code, really. Home Assistants's Mill integration stopped working. Looked the debug logs it seems there is response with house and room data but device's "isConnected" is false in JSON returned by the API. And integration does not display temp any more. Device is online and visible via official Mill app.

**Comment by Danielhiversen** [comment]
Since the API reports `isConnected" is false `  for online devices, you should report it to Mill

**Comment by ahti123** [comment]
> Since the API reports `isConnected" is false ` for online devices, you should report it to Mill

Ok, I understood that the pymill is reverse engineered usage of the Mill devices. The official Mill app (via official API I think) shows my device as "online".
Asked from the local HA community whether the integration works for them and got one reply that it has stopped working, too. But I understand it works for everybody else? Strange then.

**Comment by Danielhiversen** [comment]
pyMill uses the official API

**Comment by ahti123** [comment]
Ok, good to know.
Looked at old issues here in the repo and saw similar problem that was solved by removing and reinstalling the (phone) app. It changed situation for myself, too - now the app shows my device as offline :D 
Anyway, seems something else, not the module, indeed.
